#!/bin/bash

echo ">> Moving into deltachat-core"
pushd deltachat-core

echo ">> Recreating builddir/"
sudo rm buildir/ -rf && mkdir builddir

echo ">> Moving into builddir"
pushd builddir

echo ">> ninja"
ninja
echo ">> sudo ninja install"
sudo ninja install
echo ">> sudo ldconfig"
sudo ldconfig

echo ">> Moving back to deltachat-node"
popd
popd

echo ">> Cleaning build/ and npm install"
rm build/ -rf && npm run dev
